spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://localhost:3306/ApolloConfigDB?useSSL=false&characterEncoding=utf8
    username: root
    password: fuimazv8p

ctrip:
  appid: 100003172

server:
  port: 8090

logging:
  file: logs/100003172/apollo-adminservice.log


